version: '3.3'

services:
  db:
    image: postgres
  web:
    # image: edss_web:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ./initialize.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true