# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 01:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20180706_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='rep_1_phone',
            new_name='rep_phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rep_1_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rep_1_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rep_2_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rep_2_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rep_2_phone',
        ),
        migrations.AddField(
            model_name='company',
            name='rep',
            field=models.OneToOneField(default='9162945789', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
